# ~/.zprofile
# ------------------------------------------------------------------------------
# Welcome message
printf "New session with $USER!\n"

# Source .zshrc for login shells
if [ -f ~/.zshrc ]; then
    source ~/.zshrc
fi
